name: CI/CD for Backend (Node.js) and Frontend (Flutter Web)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Backend Node.js 설정
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Run backend tests
        run: |
          cd backend
          npm test --passWithNoTests  # 테스트 코드가 없어도 통과

      # Flutter Web 프론트엔드 설정 (Flutter stable 버전)
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # 특정 버전 대신 stable 채널 사용

      - name: Install Flutter dependencies
        run: |
          cd frontend
          flutter pub get

      - name: Build Flutter web app
        run: |
          cd frontend
          flutter build web

      # Rocky Linux로 배포
      - name: Deploy to Rocky Linux
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa suojae@192.168.10.120 << 'EOF'
            # 백엔드 배포
            cd /home/suojae/Users/jayoengchoi/WebstormProjects/fullstack-todo/backend
            git pull origin main
            npm install
            npm run build
            pm2 restart all

            # Flutter Web 프론트엔드 배포
            cd /home/suojae/Users/jayoengchoi/WebstormProjects/fullstack-todo/frontend
            rm -rf /var/www/html/*
            cp -r build/web/* /var/www/html/
            systemctl restart nginx
          EOF
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
