name: CI/CD to Rocky Linux

on:
  push:
    branches:
      - main  # main 브랜치에 푸시할 때만 실행

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to Rocky Linux via SSH
        uses: appleboy/ssh-action@v0.1.0
        with:
          host: ${{ secrets.LG_HOST }}
          username: ${{ secrets.LG_USER }}
          key: ${{ secrets.LG_SSH_KEY }}
          script: |
            cd /path/to/project/on/rocky-linux
            git pull origin main
            npm install
            pm2 restart all
            sudo systemctl restart nginx
